spring:
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY:}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}