jwt:
  access-token-key: ${ACCESS_JWT_KEY:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzOTEwYjc4OC1iYjA0LTQ2ZGUtOGIzOC0zNjhjZmUzN2FlZTYiLCJpYXQiOjE3MTY5MDAzNjgsImV4cCI6MTcxNjkwMDY2OH0.LkgMzQKsrfQ_7hod-jBj2yuIrLSIi9a9EQ-sn5CMcBU}
  access-token-expiration: ${ACCESS_JWT_EXPIRATION:3600000}  # 5 minutes