spring:
  datasource:
    url: jdbc:mysql://zigtong-db.cvwsowqaspno.ap-northeast-2.rds.amazonaws.com:3306/zigtong-db?createDatabaseIfNotExist=true
    username: admin
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect