spring:
  profiles:
    active: prod
    group:
      prod:
        - connection-prod
        - security
        - infra
      dev:
        - connection-dev
        - security
        - infra
      #test:
       # - connection-test
       # - security
logging:
  level:
    root: debug
