spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/zigtong
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    include: security
    active: dev
    group:
      prod:
        - connection-prod
        - oauth-prod
      dev:
        - dev
logging:
  level:
    root: debug