spring:
  profiles:
    active: dev
    group:
      prod:
        - connection-prod
        - security
      dev:
        - connection-dev
        - security
      #test:
       # - connection-test
       # - security
logging:
  level:
    root: debug