name: Gradle Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: ./gradlew build

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        aws s3 cp build/libs/myapp.jar s3://$AWS_S3_BUCKET/
