name: Gradle Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Inject AWS credentials into application-infra.yml
      run: |
        sed -i 's|\${S3_ACCESS_KEY}|'"${{ secrets.S3_ACCESS_KEY }}"'|' ./src/main/resources/application-infra.yml
        sed -i 's|\${S3_SECRET_KEY}|'"${{ secrets.S3_SECRET_KEY }}"'|' ./src/main/resources/application-infra.yml
        sed -i 's|\${S3_BUCKET_NAME}|'"${{ secrets.S3_BUCKET_NAME }}"'|' ./src/main/resources/application-infra.yml
